export const ActionTypes = {
  // 로그인 관련
  GET_TOKEN: 'GET_TOKEN',
  GET_TOKEN_FAIL: 'GET_TOKEN_FAIL',
  GET_TOKEN_SUCCESS: 'GET_TOKEN_SUCCESS',

  GET_USERME: 'GET_USERME',
  GET_USERME_FAIL: 'GET_USERME_FAIL',
  GET_USERME_SUCCESS: 'GET_USERME_SUCCESS',

  REFRESH_TOKEN: 'REFRESH_TOKEN',
  REFRESH_TOKEN_FAIL: 'REFRESH_TOKEN_FAIL',
  REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',

  SIGNUP: 'SIGNUP',
  SIGNUP_FAIL: 'SIGNUP_FAIL',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',

  LOGIN: 'LOGIN',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',

  LOGOUT: 'LOGOUT',

  //Article 관련

  CREATE_ARTICLE: 'CREATE_ARTICLE',
  CREATE_ARTICLE_SUCCESS: 'CREATE_ARTICLE_SUCCESS',
  CREATE_ARTICLE_FAIL: 'CREATE_ARTICLE_FAIL',

  CLEAR_TODO: 'CLEAR_TODO',
  CLEAR_TODO_SUCCESS: 'CLEAR_TODO_SUCCESS',
  CLEAR_TODO_FAIL: 'CLEAR_TODO_FAIL',

  LISTOF_ARTICLE: 'LISTOF_ARTICLE',
  LISTOF_ARTICLE_SUCCESS: 'LISTOF_ARTICLE_SUCCESS',
  LISTOF_ARTICLE_FAIL: 'LISTOF_ARTICLE_FAIL',

  DELETE_ARTICLE: 'DELETE_ARTICLE',
  DELETE_ARTICLE_SUCCESS: 'DELETE_ARTICLE_SUCCESS',
  DELETE_ARTICLE_FAIL: 'DELETE_ARTICLE_FAIL',

  RETRIEVE_ARTICLE: 'RETRIEVE_ARTICLE',
  RETRIEVE_ARTICLE_SUCCESS: 'RETRIEVE_ARTICLE_SUCCESS',
  RETRIEVE_ARTICLE_FAIL: 'RETRIEVE_ARTICLE_FAIL',

  UPDATE_ARTICLE: 'UPDATE_ARTICLE',
  UPDATE_ARTICLE_SUCCESS: 'UPDATE_ARTICLE_SUCCESS',
  UPDATE_ARTICLE_FAIL: 'UPDATE_ARTICLE_FAIL',

  UPDATE_FILES: 'UPDATE_FILES',
  UPDATE_FILES_SUCCESS: 'UPDATE_FILES_SUCCESS',
  UPDATE_FILES_FAIL: 'UPDATE_FILES_FAIL',

  LISTOF_FILES: 'LISTOF_FILES',
  LISTOF_FILES_SUCCESS: 'LISTOF_FILES_SUCCESS',
  LISTOF_FILES_FAIL: 'LISTOF_FILES_FAIL',

  DOWN_FILES : 'DOWN_FILES',
  DOWN_FILES_SUCCESS : 'DOWN_FILES_SUCCESS',
  DOWN_FILES_FAIL : 'DOWN_FILES_FAIL',

  // Reply 
  LISTOF_REPLY: 'LISTOF_REPLY',
  LISTOF_REPLY_SUCCESS: 'LISTOF_REPLY_SUCCESS',
  LISTOF_REPLY_FAIL: 'LISTOF_REPLY_FAIL',

  CREATE_REPLY: 'CREATE_REPLY',
  CREATE_REPLY_SUCCESS: 'CREATE_REPLY_SUCCESS',
  CREATE_REPLY_FAIL: 'CREATE_REPLY_FAIL',

  DELETE_REPLY: 'DELETE_REPLY',
  DELETE_REPLY_SUCCESS: 'DELETE_REPLY_SUCCESS',
  DELETE_REPLY_FAIL: 'DELETE_REPLY_FAIL',

  UPDATE_REPLY: 'UPDATE_REPLY',
  UPDATE_REPLY_SUCCESS: 'UPDATE_REPLY_SUCCESS',
  UPDATE_REPLY_FAIL: 'UPDATE_REPLY_FAIL',

  RETRIEVE_REPLY: 'RETRIEVE_REPLY',
  RETRIEVE_REPLY_SUCCESS: 'RETRIEVE_REPLY_SUCCESS',
  RETRIEVE_REPLY_FAIL: 'RETRIEVE_REPLY_FAIL',

  // Manage 관련
  REGISTER_STUDENT: 'REGISTER_STUDENT',
  REGISTER_STUDENT_SUCCESS: 'REGISTER_STUDENT_SUCCESS',
  REGISTER_STUDENT_FAIL: 'REGISTER_STUDENT_FAIL',

  REGISTER_TEACHER: 'REGISTER_TEACHER',
  REGISTER_TEACHER_SUCCESS: 'REGISTER_TEACHER_SUCCESS',
  REGISTER_TEACHER_FAIL: 'REGISTER_TEACHER_FAIL',

  LIST_STUDENT_ALL : 'LIST_STUDENT_ALL',
  LIST_STUDENT_ALL_SUCCESS : 'LIST_STUDENT_ALL_SUCCESS',
  LIST_STUDENT_ALL_FAIL : 'LIST_STUDENT_ALL_FAIL',
  LIST_TEACHER_ALL : 'LIST_TEACHER_ALL',
  LIST_TEACHER_ALL_SUCCESS : 'LIST_TEACHER_ALL_SUCCESS',
  LIST_TEACHER_ALL_FAIL : 'LIST_TEACHER_ALL_FAIL',

  // TestGroup 관련
  CREATE_TESTGROUP: 'CREATE_TESTGROUP', // 시험 생성
  CREATE_TESTGROUP_SUCCESS: "CREATE_TESTGROUP_SUCCESS", // 시험 생성 성공
  CREATE_TESTGROUP_FAIL: "CREATE_TESTGROUP_FAIL", // 시험 생성 실패

  LISTOF_TESTGROUP: 'LISTOF_TESTGROUP', // 시험 진행 중 리스트
  LISTOF_TESTGROUP_SUCCESS: 'LISTOF_TESTGROUP_SUCCESS', // 시험 진행 중 리스트 출력 성공
  LISTOF_TESTGROUP_FAIL: 'LISTOF_TESTGROUP_FAIL', // 시험 진행 중 리스트 출력 실패

  LISTOF_END_TESTGROUP: 'LISTOF_TESTGROUP', // 시험 진행 중 리스트
  LISTOF_END_TESTGROUP_SUCCESS: 'LISTOF_TESTGROUP_SUCCESS', // 시험 진행 중 리스트 출력 성공
  LISTOF_END_TESTGROUP_FAIL: 'LISTOF_TESTGROUP_FAIL', // 시험 진행 중 리스트 출력 실패

  RETRIEVE_TESTGROUP: 'RETRIEVE_TESTGROUP', // 해당 시험 설명 출력
  RETRIEVE_TESTGROUP_SUCCESS: 'RETRIEVE_TESTGROUP_SUCCESS', // 설명 출력 성공
  RETRIEVE_TESTGROUP_FAIL: 'RETRIEVE_TESTGROUP_FAIL', // 실패

  UPDATE_TESTGROUP: 'UPDATE_TESTGROUP', // 해당 시험 수정
  UPDATE_TESTGROUP_SUCCESS: 'UPDATE_TESTGROUP_SUCCESS', // 설명 출력 성공
  UPDATE_TESTGROUP_FAIL: 'UPDATE_TESTGROUP_FAIL', // 실패

  DELETE_TESTGROUP: 'DELETE_TESTGROUP', // 해당 시험 삭제
  DELETE_TESTGROUP_SUCCESS: 'DELETE_TESTGROUP_SUCCESS', // 삭제 성공
  DELETE_TESTGROUP_FAIL: 'DELETE_TESTGROUP_FAIL', // 실패

  // TestQuiz 관련
  CREATE_TEST_QUIZ: 'CREATE_TEST_QUIZ', // 시험 출제 시 문제 선택하여 testQuiz 생성
  CREATE_TEST_QUIZ_SUCCESS: 'CREATE_TEST_QUIZ_SUCCESS', // 생성 성공
  CREATE_TEST_QUIZ_FAIL: 'CREATE_TEST_QUIZ_FAIL', // 생성 실패

  LISTOF_TEST_QUIZ: 'LISTOF_TEST_QUIZ', // 시험 문제 전체 출력
  LISTOF_TEST_QUIZ_SUCCESS: 'LISTOF_TEST_QUIZ_SUCCESS', // 시험 문제 전체 출력 성공
  LISTOF_TEST_QUIZ_FAIL: 'LISTOF_TEST_QUIZ_FAIL',  // 시험 문제 전체 출력 실패

  DELETE_TEST_QUIZ: 'DELETE_TEST_QUIZ', // 시험 문제 삭제
  DELETE_TEST_QUIZ_SUCCESS: 'DELETE_TEST_QUIZ_SUCCESS', // 시험 문제 삭제 성공
  DELETE_TEST_QUIZ_FAIL: 'DELETE_TEST_QUIZ_FAIL', // 시험 문제 삭제 실패

  // StudnetAnswer 관련`
  CREATE_STUDENT_TEST: 'CREATE_STUDENT_TEST', // 학생 시험 생성
  CREATE_STUDENT_TEST_SUCCESS: 'CREATE_STUDENT_TEST_SUCCESS', // 성공
  CREATE_STUDENT_TEST_FAIL: 'CREATE_STUDENT_TEST_FAIL', // 실패

  CREATE_STUDENT_ANSWER: 'CREATE_STUDENT_ANSWER', // 학생 답 생성
  CREATE_STUDENT_ANSWER_SUCCESS: 'CREATE_STUDENT_ANSWER_SUCCESS', // 생성 성공
  CREATE_STUDENT_ANSWER_FAIL: 'CREATE_STUDENT_ANSWER_FAIL', // 실패

  UPDATE_STUDETNT_TEST_SCORE: 'UPDATE_STUDETNT_TEST_SCORE', // 학생 점수 수정 >> 원래 0점, 시험이 종료된 후 모두 점수가 수정
  UPDATE_STUDETNT_TEST_SCORE_SUCCESS: 'UPDATE_STUDETNT_TEST_SCORE_SUCCESS', // 성공
  UPDATE_STUDETNT_TEST_SCORE_FAIL: 'UPDATE_STUDETNT_TEST_SCORE_FAIL', // 실패

  LISTOF_STUDENT_TEST_SCORE: 'LISTOF_STUDENT_TEST_SCORE', // 학생 점수 보기
  LISTOF_STUDENT_TEST_SCORE_SUCCESS: 'LISTOF_STUDENT_TEST_SCORE_SUCCESS', // 점수 보기 성공
  LISTOF_STUDENT_TEST_SCORE_FAIL: 'LISTOF_STUDENT_TEST_SCORE_FAIL', // 점수 보기 실패

  LISTOF_STUDENT_ANSWER: 'LISTOF_STUDENT_ANSWER', // 학생 답 리스트
  LISTOF_STUDENT_ANSWER_SUCCESS: 'LISTOF_STUDENT_ANSWER_SUCCESS', // 학생 답 리스트 성공
  LISTOF_STUDENT_ANSWER_FAIL: 'LISTOF_STUDENT_ANSWER_FAIL', // 학생 답 리스트 실패

  COMPARE_STUDENT_TEST_ID: 'COMPARE_STUDENT_TEST_ID', //학생 문제 번호가 있는지 없는지 구분
  COMPARE_STUDENT_TEST_ID_SUCCESS: 'COMPARE_STUDENT_TEST_ID_SUCCESS', // 성공
  COMPARE_STUDENT_TEST_ID_FAIL: 'COMPARE_STUDENT_TEST_ID_FAIL', // 실패

  // MyInfo 관련
  READ_MYINFO: 'READ_MYINFO',
  READ_MYINFO_SUCCESS: 'READ_MYINFO_SUCCESS',
  READ_MYINFO_FAIL: 'READ_MYINFO_FAIL',

  UPDATE_MYINFO: 'UPDATE_MYINFO',
  UPDATE_MYINFO_SUCCESS: 'UPDATE_MYINFO_SUCCESS',
  UPDATE_MYINFO_FAIL: 'UPDATE_MYINFO_FAIL',


  // AttendLog 관련
  LISTOF_ATTENDLOG: 'LISTOF_ATTENDLOG',
  LISTOF_ATTENDLOG_SUCCESS: 'LISTOF_ATTENDLOG_SUCCESS',
  LISTOF_ATTENDLOG_FAIL: 'LISTOF_ATTENDLOG_FAIL',

  // ForgotUserInfo 관련
  FIND_USERID: 'FIND_USERID',
  lFIND_USERID_SUCCESS: 'FIND_USERID_SUCCESS',
  FIND_USERID_FAIL: 'FIND_USERID_FAIL',
  
  FIND_PASSWORD: 'FIND_PASSWORD',
  FIND_PASSWORD_SUCCESS: 'FIND_PASSWORD_SUCCESS',
  FIND_PASSWORD_FAIL: 'FIND_PASSWORD_FAIL',
  
  COMPARE_USERINFO: 'COMPARE_USERINFO',
  COMPARE_USERINFO_SUCCESS: 'COMPARE_USERINFO_SUCCESS',
  COMPARE_USERINFO_FAIL: 'COMPARE_USERINFO_FAIL',

  // Quiz 관련

  CREATE_QUIZ: 'CREATE_QUIZ',
  CREATE_QUIZ_SUCCESS: 'CREATE_QUIZ_SUCCESS',
  CREATE_QUIZ_FAIL: 'CREATE_QUIZ_FAIL',

  //   CLEAR_TODO: 'CLEAR_TODO',
  //   CLEAR_TODO_SUCCESS: 'CLEAR_TODO_SUCCESS',
  //   CLEAR_TODO_FAIL: 'CLEAR_TODO_FAIL',

  LISTOF_QUIZ: 'LISTOF_QUIZ',
  LISTOF_QUIZ_SUCCESS: 'LISTOF_QUIZ_SUCCESS',
  LISTOF_QUIZ_FAIL: 'LISTOF_QUIZ_FAIL',

  DELETE_QUIZ: 'DELETE_QUIZ',
  DELETE_QUIZ_SUCCESS: 'DELETE_QUIZ_SUCCESS',
  DELETE_QUIZ_FAIL: 'DELETE_QUIZ_FAIL',

  RETRIEVE_QUIZ: 'RETRIEVE_QUIZ',
  RETRIEVE_QUIZ_SUCCESS: 'RETRIEVE_QUIZ_SUCCESS',
  RETRIEVE_QUIZ_FAIL: 'RETRIEVE_QUIZ_FAIL',

  UPDATE_QUIZ: 'UPDATE_QUIZ',
  UPDATE_QUIZ_SUCCESS: 'UPDATE_QUIZ_SUCCESS',
  UPDATE_QUIZ_FAIL: 'UPDATE_QUIZ_FAIL',

   // Homework 관련
   CREATE_HOMEWORK: 'CREATE_HOMEWORK',
   CREATE_HOMEWORK_SUCCESS: 'CREATE_HOMEWORK_SUCCESS',
   CREATE_HOMEWORK_FAIL: 'CREATE_HOMEWORK_FAIL',
 
   LISTOF_HOMEWORK: 'LISTOF_HOMEWORK',
   LISTOF_HOMEWORK_SUCCESS: 'LISTOF_HOMEWORK_SUCCESS',
   LISTOF_HOMEWORK_FAIL: 'LISTOF_HOMEWORK_FAIL',
 
   LISTOF_ENDEDHOMEWORK: 'LISTOF_ENDEDHOMEWORK',
   LISTOF_ENDEDHOMEWORK_SUCCESS: 'LISTOF_ENDEDHOMEWORK_SUCCESS',
   LISTOF_ENDEDHOMEWORK_FAIL: 'LISTOF_ENDEDHOMEWORK_FAIL',
 
   DELETE_HOMEWORK: 'DELETE_HOMEWORK',
   DELETE_HOMEWORK_SUCCESS: 'DELETE_HOMEWORK_SUCCESS',
   DELETE_HOMEWORK_FAIL: 'DELETE_HOMEWORK_FAIL',
 
   RETRIEVE_HOMEWORK: 'RETRIEVE_HOMEWORK',
   RETRIEVE_HOMEWORK_SUCCESS: 'RETRIEVE_HOMEWORK_SUCCESS',
   RETRIEVE_HOMEWORK_FAIL: 'RETRIEVE_HOMEWORK_FAIL',
 
   UPDATE_HOMEWORK: 'UPDATE_HOMEWORK',
   UPDATE_HOMEWORK_SUCCESS: 'UPDATE_HOMEWORK_SUCCESS',
   UPDATE_HOMEWORK_FAIL: 'UPDATE_HOMEWORK_FAIL',
 
   // HwArticle 관련
   CREATE_HWARTICLE: 'CREATE_HWARTICLE',
   CREATE_HWARTICLE_SUCCESS: 'CREATE_HWARTICLE_SUCCESS',
   CREATE_HWARTICLE_FAIL: 'CREATE_HWARTICLE_FAIL',
 
   LISTOF_HWARTICLE: 'LISTOF_HWARTICLE',
   LISTOF_HWARTICLE_SUCCESS: 'LISTOF_HWARTICLE_SUCCESS',
   LISTOF_HWARTICLE_FAIL: 'LISTOF_HWARTICLE_FAIL',
 
   LISTOF_ENDEDHWARTICLE: 'LISTOF_HWARTICLE',
   LISTOF_ENDEDHWARTICLE_SUCCESS: 'LISTOF_HWARTICLE_SUCCESS',
   LISTOF_ENDEDHWARTICLE_FAIL: 'LISTOF_HWARTICLE_FAIL',
 
   DELETE_HWARTICLE: 'DELETE_HWARTICLE',
   DELETE_HWARTICLE_SUCCESS: 'DELETE_HWARTICLE_SUCCESS',
   DELETE_HWARTICLE_FAIL: 'DELETE_HWARTICLE_FAIL',
 
   RETRIEVE_HWARTICLE: 'RETRIEVE_HWARTICLE',
   RETRIEVE_HWARTICLE_SUCCESS: 'RETRIEVE_HWARTICLE_SUCCESS',
   RETRIEVE_HWARTICLE_FAIL: 'RETRIEVE_HWARTICLE_FAIL',
 
   UPDATE_HWARTICLE: 'UPDATE_HWARTICLE',
   UPDATE_HWARTICLE_SUCCESS: 'UPDATE_HWARTICLE_SUCCESS',
   UPDATE_HWARTICLE_FAIL: 'UPDATE_HWARTICLE_FAIL',
 
   FINDMY_HWARTICLE: 'FINDMY_HWARTICLE',
   FINDMY_HWARTICLE_SUCCESS: 'FINDMY_HWARTICLE_SUCCESS',
   FINDMY_HWARTICLE_FAIL: 'FINDMY_HWARTICLE_FAIL',
 
   FINDMY_HWARTICLE_FORTEACHER: 'FINDMY_HWARTICLE_FORTEACHER',
   FINDMY_HWARTICLE_FORTEACHER_SUCCESS: 'FINDMY_HWARTICLE_FORTEACHER_SUCCESS',
   FINDMY_HWARTICLE_FORTEACHER_FAIL: 'FINDMY_HWARTICLE_FORTEACHER_FAIL',

   // HwReply 
   LISTOF_HWREPLY: 'LISTOF_HWREPLY',
   LISTOF_HWREPLY_SUCCESS: 'LISTOF_HWREPLY_SUCCESS',
   LISTOF_HWREPLY_FAIL: 'LISTOF_HWREPLY_FAIL',
 
   CREATE_HWREPLY: 'CREATE_HWREPLY',
   CREATE_HWREPLY_SUCCESS: 'CREATE_HWREPLY_SUCCESS',
   CREATE_HWREPLY_FAIL: 'CREATE_HWREPLY_FAIL',
 
   DELETE_HWREPLY: 'DELETE_HWREPLY',
   DELETE_HWREPLY_SUCCESS: 'DELETE_HWREPLY_SUCCESS',
   DELETE_HWREPLY_FAIL: 'DELETE_HWREPLY_FAIL',
 
   UPDATE_HWREPLY: 'UPDATE_HWREPLY',
   UPDATE_HWREPLY_SUCCESS: 'UPDATE_HWREPLY_SUCCESS',
   UPDATE_HWREPLY_FAIL: 'UPDATE_HWREPLY_FAIL',
 
   RETRIEVE_HWREPLY: 'RETRIEVE_HWREPLY',
   RETRIEVE_HWREPLY_SUCCESS: 'RETRIEVE_HWREPLY_SUCCESS',
   RETRIEVE_HWREPLY_FAIL: 'RETRIEVE_HWREPLY_FAIL',

  // Counsel 관련
  READ_COUNSEL_STUDENTS: 'READ_COUNSEL_STUDENTS',
  READ_COUNSEL_STUDENTS_SUCCESS: 'READ_COUNSEL_STUDENTS_SUCCESS',
  READ_COUNSEL_STUDENTS_FAIL: 'READ_COUNSEL_STUDENTS_FAIL',

  READ_COUNSEL: 'READ_COUNSEL',
  READ_COUNSEL_SUCCESS: 'READ_COUNSEL_SUCCESS',
  READ_COUNSEL_FAIL: 'READ_COUNSEL_FAIL',

  UPDATE_COUNSEL: 'UPDATE_COUNSEL',
  UPDATE_COUNSEL_SUCCESS: 'UPDATE_COUNSEL_SUCCESS',
  UPDATE_COUNSEL_FAIL: 'UPDATE_COUNSEL_FAIL',


  // Roadmap 관련
  LISTOF_ROADMAP: 'LISTOF_ROADMAP',
  LISTOF_ROADMAP_SUCCESS: 'LISTOF_ROADMAP_SUCCESS',
  LISTOF_ROADMAP_FAIL: 'LISTOF_ROADMAP_FAIL',

  RETRIEVE_ROADMAP: 'RETRIEVE_ROADMAP',
  RETRIEVE_ROADMAP_SUCCESS: 'RETRIEVE_ROADMAP_SUCCESS',
  RETRIEVE_ROADMAP_FAIL: 'RETRIEVE_ROADMAP_FAIL',

  UPDATE_ROADMAP: 'UPDATE_ROADMAP',
  UPDATE_ROADMAP_SUCCESS: 'UPDATE_ROADMAP_SUCCESS',
  UPDATE_ROADMAP_FAIL: 'UPDATE_ROADMAP_FAIL',

  GET_ROADMAPLAST : 'GET_ROADMAPLAST',
  GET_ROADMAPLAST_SUCCESS : 'GET_ROADMAPLAST_SUCCESS',
  GET_ROADMAPLAST_FAIL : 'GET_ROADMAPLAST_FAIL',

  // ClassGroup 관련
  REGISTER_CLASSGROUP: 'REGISTER_CLASSGROUP',
  REGISTER_CLASSGROUP_SUCCESS: 'REGISTER_CLASSGROUP_SUCCESS',
  REGISTER_CLASSGROUP_FAIL: 'REGISTER_CLASSGROUP_FAIL',

  LIST_CLASS_ALL : 'LIST_CLASS_ALL',
  LIST_CLASS_ALL_SUCCESS : 'LIST_CLASS_ALL_SUCCESS',
  LIST_CLASS_ALL_FAIL : 'LIST_CLASS_ALL_FAIL',

  // PointLog 관련
  READ_MYPOINTLOG: 'READ_MYPOINTLOG',
  READ_MYPOINTLOG_SUCCESS: 'READ_MYPOINTLOG_SUCCESS',
  READ_MYPOINTLOG_FAIL: 'READ_MYPOINTLOG_FAIL',

  //Profile 관련
  GET_STUDENT_PROFILE: 'GET_STUDENT_PROFILE',
  GET_STUDENT_PROFILE_SUCCESS: 'GET_STUDENT_PROFILE_SUCCESS',
  GET_STUDENT_PROFILE_FAIL: 'GET_STUDENT_PROFILE_FAIL',

  GET_TEACHER_PROFILE: 'GET_TEACHER_PROFILE',
  GET_TEACHER_PROFILE_SUCCESS: 'GET_TEACHER_PROFILE_SUCCESS',
  GET_TEACHER_PROFILE_FAIL: 'GET_TEACHER_PROFILE_FAIL',
  
  GET_ADMIN_PROFILE: 'GET_ADMIN_PROFILE',
  GET_ADMIN_PROFILE_SUCCESS: 'GET_ADMIN_PROFILE_SUCCESS',
  GET_ADMIN_PROFILE_FAIL: 'GET_ADMIN_PROFILE_FAIL'

};

export const Errors = {
  UnknownError: "Unknown error!"
};
